spring:
  datasource:
    url: jdbc:mysql://localhost:3306/libary?characterEncoding=utf8&useSSL=true&serverTimezone=GMT
    username: root
    password: 12xuhua12
    driver-class-name: com.mysql.jdbc.Driver

server:
  port: 8181

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.springvue.Model



